import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header>
          {children}
          
        </Header>
        
                        <main className="flex-1 overflow-auto p-3 md:p-6 bg-gradient-to-br from-background via-background to-blue-50/30">
          <div className="animate-in slide-in-from-right-5 duration-300 max-w-full">

          </div>
        </main>
      </body>
    </html>
  );
}
